### ISSUE TITLE
Bug: bin remove leads to "corrupt" .bin/config.json file

### ISSUE THREAD

**Issue by breml** [marcosnils/bin#58] opened 2021-03-18 20:19 UTC
I added 3 binaries with `bin` and then removed one of the binaries again with `bin remove <binary>`.
After this I had a look at the `.bin/config.json` file and I found, that the file still contains fragments of the removed tool like this:

```json
{
    "default_path": "<redacted>/bin",
    "bins": {
        "<redacted>/bin/bin": {
            "path": "<redacted>/bin/bin",
            "remote_name": "bin",
            "version": "v0.4.0",
            "hash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
            "url": "github.com/marcosnils/bin",
            "provider": "github"
        },
        "<redacted>/bin/bit": {
            "path": "<redacted>/bin/bit",
            "remote_name": "bit",
            "version": "v1.0.4",
            "hash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
            "url": "https://github.com/chriswalz/bit/releases/tag/v1.0.4",
            "provider": ""
        }
    }
}
 "<redacted>/bin/syncthing": {
            "path": "<redacted>/bin/syncthing",
            "remote_name": "syncthing",
            "version": "v1.14.0",
            "hash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
            "url": "github.com/syncthing/syncthing",
            "provider": "github"
        }
    }
}
```

To me, it looks like the the content of the config file is not reset before the changed config file is written back to disk. 

https://github.com/marcosnils/bin/blob/8d946cb240845c92bff704ce2c0a5a1527e36126/pkg/config/config.go#L99

Additionally, I feel like the permissions for this file should not default to `0666` but something more restricted, e.g. `0600` or `0640`.

**Comment by marcosnils** [comment] 2021-03-18 20:28
> Additionally, I feel like the permissions for this file should not default to `0666` but something more restricted, e.g. `0600` or `0640`.

I guess we can change it to 664. That's the default when you `touch` a new file.




> To me, it looks like the the content of the config file is not reset before the changed config file is written back to disk.

Weird bug indeed.. Just tried adding and removing a binary and couldn't reproduce. Are you able to repro consistently?

**Comment by marcosnils** [comment] 2021-03-18 20:34
> > To me, it looks like the the content of the config file is not reset before the changed config file is written back to disk.

Think I've found what's happening. We're not actually closing the file after writing in the `write` method. So we can't be sure that `write` actually flushes the file after returns. I just saw that you're changing this in your fork, mind adding this please?

**Closed** 2021-03-19 19:48 UTC
